apiVersion: apps/v1
kind: Deployment
metadata:
  name: recreate-app
  labels:
    app: recreate-app
    version: "1"
spec:
  replicas: 3
  strategy:
    type: Recreate    # All pods terminated before new ones created
  selector:
    matchLabels:
      app: recreate-app
  template:
    metadata:
      labels:
        app: recreate-app
        version: "1"
    spec:
      containers:
      - name: web-server
        image: nginx:1.21
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html  
      volumes:
      - name: html
        configMap:
          name: recreate-app-v1  # This ConfigMap contains our custom index.html
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: recreate-app-v1
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head><title>Recreate - V1</title></head>
    <body>
      <h1>Recreate Deployment</h1>
      <h2>Version 1.0</h2>
      <p>Old version before recreate</p>
    </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: recreate-app-service
spec:
  type: LoadBalancer
  selector:
    app: recreate-app
  ports:
  - port: 80
    targetPort: 80
