apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-app
  labels:
    app: web-app
    track: canary
spec:
  replicas: 1  # 10% din trafic (1 din 10 pod-uri)
  selector:
    matchLabels:
      app: web-app
      track: canary
  template:
    metadata:
      labels:
        app: web-app
        track: canary
        version: "2"
    spec:
      containers:
      - name: web
        image: nginx:1.21
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html
        configMap:
          name: web-app-v2
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: web-app-v2
data:
  index.html: |
    <html><head><title>Canary V2</title></head>
    <body style="background:#ffeb3b">
    <h1>🟡 Canary Version 2.0</h1>
    <p>10% of traffic here - testing!</p>
    </body></html>
